### ISSUE TITLE
希望添加一个搜索功能

### ISSUE THREAD

**Issue by jidesheng6** [UlyssesWu/BAML-Translator#1]
导出到csv虽然方便，但是有时候会出现莫名其妙的问题，比如加载回来会变成双倍的字符数量，有些字段类型丢失，最好是在内部添加搜索功能，万分感谢

**Comment by UlyssesWu** [comment]
会考虑增加搜索功能的。
不过如果你愿意，希望能提供下上面说的两个问题的复现场景（程序文件和csv等），可发送到我的邮箱。

**Comment by jidesheng6** [comment]
非常感谢您的回复，完整程序可能比较大，大概（300MB左右）

我当时做的操作如下：


1、加载PACX.exe文件，显示出BAML文件内容，进行修改，随后使用“处理程序集”，在目录下生成CSV文件。（大概是738个条目）


2、使用EXCEL打开CSV文件，调整两边列宽，随后保存，EXCEL提示CSV不兼容，是否要保存（这里它好像会改什么东西），我选择“是”（Office版本：2010）。


3、返回您做的BAML本地化程序，使用快速读取功能，出现1575个左右条目，同时开启“排序功能”。类型排序，有一部分的类型名称为“空”，并非BAML。


4、使用SN开头的，一个编辑CSV的软件，重复操作，发现只是概率性出现上述问题，有点摸不清。


还请您按照上述步骤复现一下，但是这么操作也可能不会出现问题，有点搞不懂。

**Comment by UlyssesWu** [comment]
已收到样本，后续有空会研究下，由于空闲时间不多，可能会优先解决bug。

> 有一部分的类型名称为“空”

这个复现了，后面会研究下问题所在。

> 使用快速读取功能，出现1575个左右条目

我试着汉化了一个条目，最后多出来3个类型为空的条目。感觉问题是出在其中的某些特殊符号上（比如引号），待研究。

> EXCEL提示CSV不兼容，是否要保存

这个没有复现，Excel直接保存成功了。我使用的是Office 365（等同于2019）。建议用diff工具对比下保存前后的csv有什么区别。

**Comment by UlyssesWu** [comment]
![image](https://user-images.githubusercontent.com/4312781/136703659-164cdf14-3e0f-4f1b-90f1-63a866140e2c.png)
事实上Excel的默认行为确实会更改部分文本（单元格格式），导致重新保存后的文本对不上，难顶。
后续再考虑导出成xlsx好了。

**Comment by jidesheng6** [comment]
辛苦辣，其实导出不导出无所谓的，能在程序内搜索到文本就可以啦，尽量不离开界面操作，因为我实际用的过程会出现这样一个担忧：
当我打开csv文件的时候，程序要不要关闭
当我加载了exe导出了csv，我修改完会不会被锁定
当我导出的时候，到底要点哪个才能把内容都导出来。


我在尝试本地化的时候因为这些纠结了很久，然后就在测试不同编辑模式的影响，有时候碰到出问题地方就要把之前汉化的东西再汉化一次。所以我觉得程序内加入搜索功能会方便一点，起码不用去测试导出文件担心有bug什么的。

**Comment by UlyssesWu** [comment]
https://github.com/UlyssesWu/BAML-Translator/releases/tag/v2.2.0

2.2版本已增加了过滤列内容的功能，尽管和搜索并不完全等价，但应该能满足基本的搜索需求。（主要是这个实现起来简单。）

**Comment by jidesheng6** [comment]
感谢^_^











发自我的iPhone

---原始邮件---
发件人: "Ulysses ***@***.***&gt;
发送时间: 2021年10月11日(周一) 凌晨0:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [UlyssesWu/BAML-Translator] 希望添加一个搜索功能 (#1)




 
https://github.com/UlyssesWu/BAML-Translator/releases/tag/v2.2.0
 
2.2版本已增加了过滤列内容的功能，尽管和搜索并不完全等价，但应该能满足基本的搜索需求。（主要是这个实现起来简单。）

**Comment by jidesheng6** [comment]
您好，我最近刚好有时间汉化了上次发给您的样本，加了过滤功能的使用效率提高了许多，想给您提个建议，同时我发现了一个问题：
关于建议：可以把过滤框做的大一点，方便输入。
发现的问题：当过滤内容的时候误触到了切换主题时，删除过滤内容无法展示所有条目，同时也无法重新过滤，需要关闭软件重新加载。

**Comment by UlyssesWu** [comment]
![image](https://user-images.githubusercontent.com/4312781/144736952-afaceadd-22d2-4d6c-bf37-47a69019908b.png)

> 可以把过滤框做的大一点

做大一点大概是这种感觉？

> 删除过滤内容无法展示所有条目

这个没能复现，或者说你描述的操作其实不是真正引发这个问题的原因。如果你发现有时点了过滤框的x之后过滤并没有更新，你还可以在你刚点x的那个过滤框里随便输入什么再删掉，强行触发一次过滤试试，而不必关闭软件。

**Comment by jidesheng6** [comment]
对的，其实最好就是把原文那一行直接变成搜索框，行高可以拉高一点，主要是行高太小了
第二点那个其实无所谓了，因为当时实不小心碰到了切换亮系/暗系主题那个开关，谢谢您回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "UlyssesWu/BAML-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月5日(星期天) 下午3:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [UlyssesWu/BAML-Translator] 希望添加一个搜索功能 (#1)





 

  
可以把过滤框做的大一点
  
做大一点大概是这种感觉？
  
删除过滤内容无法展示所有条目
  
这个没能复现，或者说你描述的操作其实不是真正引发这个问题的原因。如果你发现有时点了过滤框的x之后过滤并没有更新，你还可以在你刚点x的那个过滤框里随便输入什么再删掉，强行触发一次过滤试试，而不必关闭软件。

**Comment by UlyssesWu** [comment]
2.3版本已进行相应的调整。如果有其他方面的问题，还可继续发表issue或discussion。

**Comment by UlyssesWu** [comment]
你提到的另一个问题我也可以复现了，这是个比较奇妙的bug，短期内可能无法解决，目前你只要随便选中表格中的任意数据或者清空最后使用的搜索框，再进行一次过滤操作应该就可以了。

**Comment by jidesheng6** [comment]
好的，辛苦你了 非常感觉，软件特别好用 赞！











发自我的iPhone

---原始邮件---
发件人: "Ulysses ***@***.***&gt;
发送时间: 2021年12月5日(周日) 晚上11:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [UlyssesWu/BAML-Translator] 希望添加一个搜索功能 (#1)




 
你提到的另一个问题我也可以复现了，这是个比较奇妙的bug，短期内可能无法解决，目前你只要随便选中表格中的任意数据或者清空最后使用的搜索框，再进行一次过滤操作应该就可以了。
