### ISSUE TITLE
有考虑增加字串拆分吗

### ISSUE THREAD

**Issue by linluz** [UlyssesWu/BAML-Translator#2]

**Comment by linluz** [comment]
比如说 open 在标题咱们会翻译成打开 在菜单或者某些带快捷键的按钮时 为了保持按钮功能 必须拆分翻译成 打开(&O)

**Comment by UlyssesWu** [comment]
如果原文有快捷键功能，它应该是 `_Open`，否则它也是没有快捷键的，遇到`_Open`时才翻译成`打开(_O)`。
