### ISSUE TITLE
The save of 2.3.1 still failed. Strange!

### ISSUE THREAD

**Issue by rmhh888** [UlyssesWu/BAML-Translator#3]
![T`986D)W2{ I 0_()D(ZIE](https://user-images.githubusercontent.com/120655657/207926449-50aa9b14-8f16-4f8a-8bd5-e111cd90d59a.png)
The save of 2.3.1 still failed. Strange!

**Comment by UlyssesWu** [comment]
Provide sample dll or your issue will be closed.

**Comment by rmhh888** [comment]
I went back to my hometown today. I'll send it back to you



---Original---
From: ***@***.***&gt;
Date: Fri, Dec 16, 2022 10:09 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [UlyssesWu/BAML-Translator] The save of 2.3.1 still failed.Strange! (Issue #3)




 
Provide sample dll or your issue will be closed.

**Comment by rmhh888** [comment]
save of 2.3.1 still failed




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "UlyssesWu/BAML-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月16日(星期五) 上午10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [UlyssesWu/BAML-Translator] The save of 2.3.1 still failed. Strange! (Issue #3)





 
Provide sample dll or your issue will be closed.

**Comment by rmhh888** [comment]
> Provide sample dll or your issue will be closed.
Has it just been sent to you? Please fix it. Is this a bug!

**Comment by UlyssesWu** [comment]
> Has it just been sent to you?

No, I haven't received anything. If you don't know how to send a file with email, you can just upload it here (on github).

**Comment by rmhh888** [comment]
The attachment is the dll file



---Original---
From: ***@***.***&gt;
Date: Fri, Dec 16, 2022 20:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [UlyssesWu/BAML-Translator] The save of 2.3.1 still failed.Strange! (Issue #3)




  
Has it just been sent to you?
  
No, I haven't received anything. If you don't know how to send a file with email, you can just upload it here (on github).

**Comment by UlyssesWu** [comment]
Oh come on, stop trying to attach the file on the reply mail, it won't be sent to me. 
Just send a mail to my email address or upload it somewhere.

**Comment by rmhh888** [comment]
https://workupload.com/file/k2zDHcUN6Nd




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "UlyssesWu/BAML-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月16日(星期五) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [UlyssesWu/BAML-Translator] The save of 2.3.1 still failed. Strange! (Issue #3)





 
Oh come on, stop trying to attach the file on the reply mail, it won't be sent to me.
 Just send a mail to my email address or upload it somewhere.

**Comment by UlyssesWu** [comment]
The dll is damaged possibly due to deobfuscation. There is nothing I can do for it. There is no support for obfuscated dlls.
If it works, that's just lucky; if it doesn't, you find another way to fix it by yourself.
The damaged method is `XsmpMax.DragDrops.DragDrop/<>c::method_0(System.Windows.Point)`.
